apiVersion: v1
kind: Namespace
metadata:
  name: namespace1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app1
  namespace: namespace1
  labels:
    app: simple-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-app1
  template:
    metadata:
      labels:
        app: simple-app1
    spec:
      containers:
      - name: simple-app1
        image: ahmed862/simple-app1
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: simple-app1-service
  namespace: namespace1
spec:
  type: LoadBalancer
  selector:
    app: simple-app1
  ports:
  - protocol: TCP
    port: 9000   # الخارج 
    targetPort: 80  
